set -g default-terminal "tmux-256color"
set -g mouse on
set -as terminal-overrides ",*:Tc"

# 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
# 
# Set parent terminal title to reflect current window in tmux session 
set -g set-titles on
set -g set-titles-string "#I:#W"
set -g status-position top

# Needed by Neovim LSP for diagnostic undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'

# Needed by the image.nvim plugin
set -gq allow-passthrough on
set -g visual-activity off

# Alternate session
# Switch between the last 2 tmux sessions, similar to 'cd -' in the terminal
# I use this in combination with the `choose-tree` to sort sessions by time
# Otherwise, by default, sessions are sorted by name, and that makes no sense
# -l stands for `last session`, see `man tmux`
unbind Space
bind-key Space switch-client -l

bind s choose-tree -Zs -O time -F "#{session_windows}"

# Increase scroll history
set-option -g history-limit 10000

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Reload the tmux configuration, display a 2 second message
unbind C-r
bind C-r source-file ~/.config/tmux/tmux.conf

# new window and retain cwd
bind c new-window -c "#{pane_current_path}"

# Rename session and window
unbind r
unbind ,
bind r command-prompt -I "#{window_name}" "rename-window '%%'"
bind R command-prompt -I "#{session_name}" "rename-session '%%'"

# Split panes
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Border lines between panes are thicker
set -g pane-border-lines double

set -g escape-time 10
set -g focus-events on
set -g set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u

bind -n S-Left  previous-window
bind -n S-Right next-window

# This enables vim nagivation
# If for example I'm in the scrolling mode (yellow) can navigate with vim motions
# search with /, using v for visual mode, etc
set -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Detach from session
bind d detach
bind D if -F '#{session_many_attached}' \
    'confirm-before -p "Detach other clients? (y/n)" "detach -a"' \
    'display "Session has only 1 client attached"'


set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_status_style "rounded"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -ag status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
 
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-b'

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_connect_separator "no"

# If nested, send the prefix through to the inner tmux
bind-key a send-prefix

run '~/.config/tmux/plugins/tpm/tpm'

